add_newline = false
format = "$directory$git_branch$git_status$cmd_duration$time$line_break$character"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[cmd_duration]
format = "[$duration]($style) "

[time]
disabled = false
time_format = "%R"
format = "[$time]($style)"
